version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ${PGCONTAINERNAME}
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USERPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /mnt/HC_Volume_102742537/DockerVolumes/postgres_data:/var/lib/postgresql/data
    healthcheck: # Voeg een healthcheck toe voor betrouwbaarheid
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PGADMINCONTAINERNAME}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMINMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMINPASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
      # PGADMIN_ENABLE_TLS: "True" # Deze regel is uitgeschakeld
      # PGADMIN_LISTEN_PORT: "443" # Deze regel is uitgeschakeld
    ports:
      - "5050:80" # pgAdmin luistert nu op poort 80 (HTTP) intern
    depends_on:
      postgres:
        condition: service_healthy # Wacht tot PostgreSQL gezond is
    volumes:
      - /mnt/HC_Volume_102742537/DockerVolumes/pgadmin_data:/var/lib/pgadmin