version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ${PGCONTAINERNAME}
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USERPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /mnt/HC_Volume_102742537/DockerVolumes/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PGADMINCONTAINERNAME}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMINMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMINPASSWORD}
      PGADMIN_ENABLE_TLS: "True"
    ports:
      - "82:443"
    depends_on:
      - postgres
    volumes:
      - /mnt/HC_Volume_102742537/DockerVolumes/pgadmin_data:/var/lib/pgadmin